### ISSUE TITLE
How to get current playing song info.

### ISSUE THREAD

**Issue by lovebdsobuj** [dylanmaryk/InsanityRadio-Android#2]
I change stream url, but song tag info not showing correctly, What I need to do for this?

**Comment by dylanmaryk** [comment]
Do you mean you're not getting the correct metadata? If so, it might be a problem with the stream itself.

**Comment by lovebdsobuj** [comment]
Yes, you got it right, 
My stream url broadcast Bengali songs but metadata show English songs title,artist name.
What about you?

**Comment by dylanmaryk** [comment]
Which line of code is returning the metadata?

**Comment by dylanmaryk** [comment]
The data returned by the methods in DataModel is specific to Insanity Radio.

**Comment by lovebdsobuj** [comment]
> The data returned by the methods in DataModel is specific to Insanity Radio.

Yes, you say right.

[app.json](http://www.insanityradio.com/app.json) is automatic generate? 

Can I get this?

**Comment by dylanmaryk** [comment]
Yes, it is generated automatically server-side, based on data specific to Insanity Radio, such as the schedule.

**Comment by lovebdsobuj** [comment]
If you don't mind,
Can I get server-side script for generate audio metadata automatically.

**Comment by dylanmaryk** [comment]
It wouldn't be much help to you. The JSON is based on data from databases and text files on our server, which themselves are generated from other sources. You can have a look anyway if you still want to.

**Comment by lovebdsobuj** [comment]
Yes, I want to look it... Because Now playing song, artist name comes from Icycast server, automatically, right.
It's come from Icycast server `{"nowPlaying":{"song":"Take Me Back","artist":"Stryder, Tinchy Feat. Taio Cruz"},`
and next part is maybe text file, for `currentShow` & `Schedule` right?

**Comment by dylanmaryk** [comment]
No, they come from a text file which Myriad writes to.

**Comment by dylanmaryk** [comment]
https://gist.github.com/dylanmaryk/bcbe4a7d4ed87a5ee95c
https://gist.github.com/dylanmaryk/ba6fc842320027c93105

**Comment by lovebdsobuj** [comment]
Hard thing for me, but thanks to you for share it...
